M48
; DRILL file {KiCad (6.0.7)} date Tue Nov  7 16:40:34 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-11-07T16:40:34+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.500
%
G90
G05
T1
X250.926Y-176.992
X274.167Y-252.049
X344.525Y-252.125
X367.766Y-176.992
T0
M30
